# Stonecutter
stonecutter_enabled_platforms=fabric, forge

# Java
java.version=17

# Minecraft
minecraft_version=1.20.1
min_minecraft_version=1.20

# Mappings
deps.parchment=2023.09.03

# Fabric
deps.fabric_loader=0.19.0
deps.fabric_api=0.92.6

# Forge
deps.forge=47.4.12

# NeoForge
deps.neoforge=

# Dependencies
deps.resourceful_lib.mc=1.20.1
deps.resourceful_lib.lib=2.1.29
deps.yacl=3.6.6+1.20.1
deps.mod_menu=7.2.2
deps.trinkets=3.7.1
deps.curios=5.4.5+1.20.1
