package com.faboslav.friendsandfoes.client.render.entity.animation;

import com.faboslav.friendsandfoes.entity.animation.Animation;
import com.faboslav.friendsandfoes.entity.animation.Keyframe;
import com.faboslav.friendsandfoes.entity.animation.Transformation;
import com.faboslav.friendsandfoes.entity.animation.VectorHelper;

import java.util.ArrayList;

public final class RascalAnimations
{
	public static final KeyframeAnimation IDLE;
	public static final KeyframeAnimation NOD;
	public static final KeyframeAnimation GIVE_REWARD;
	public static final KeyframeAnimation WALK;
	public static final ArrayList<KeyframeAnimation> ANIMATIONS;

	public RascalAnimations() {
	}

	static {
		IDLE = new KeyframeAnimation("idle", Animation.Builder.create(2f).looping()
			.addBoneAnimation("head",
				new Transformation(Transformation.Type.TRANSLATE,
					new Keyframe(0f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.1676667f, VectorHelper.createTranslationalVector(0f, 0.25f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(2f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("head",
				new Transformation(Transformation.Type.ROTATE,
					new Keyframe(0f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.1676667f, VectorHelper.createRotationalVector(-2.5f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(2f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("leftArm",
				new Transformation(Transformation.Type.TRANSLATE,
					new Keyframe(0f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.1676667f, VectorHelper.createTranslationalVector(0f, 0.25f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(2f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("leftArm",
				new Transformation(Transformation.Type.ROTATE,
					new Keyframe(0f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.5f, VectorHelper.createRotationalVector(-3f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.1676667f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.5834333f, VectorHelper.createRotationalVector(1.5f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(2f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("rightArm",
				new Transformation(Transformation.Type.TRANSLATE,
					new Keyframe(0f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.1676667f, VectorHelper.createTranslationalVector(0f, 0.25f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(2f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("rightArm",
				new Transformation(Transformation.Type.ROTATE,
					new Keyframe(0f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.5f, VectorHelper.createRotationalVector(-3f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.1676667f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.5834333f, VectorHelper.createRotationalVector(1.5f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(2f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("bag",
				new Transformation(Transformation.Type.TRANSLATE,
					new Keyframe(0f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.1676667f, VectorHelper.createTranslationalVector(0f, 0.25f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(2f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("bag",
				new Transformation(Transformation.Type.ROTATE,
					new Keyframe(0f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.1676667f, VectorHelper.createRotationalVector(0.3f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(2f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("body",
				new Transformation(Transformation.Type.TRANSLATE,
					new Keyframe(0f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.1676667f, VectorHelper.createTranslationalVector(0f, 0.25f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(2f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("body",
				new Transformation(Transformation.Type.ROTATE,
					new Keyframe(0f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.1676667f, VectorHelper.createRotationalVector(0.3f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(2f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR))).build()
		);
		NOD = new KeyframeAnimation("nod", Animation.Builder.create(0.4167f)
			.addBoneAnimation("head",
				new Transformation(Transformation.Type.TRANSLATE,
					new Keyframe(0f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.1667f, VectorHelper.createTranslationalVector(0f, 2f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.4167f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("head",
				new Transformation(Transformation.Type.ROTATE,
					new Keyframe(0f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.0833f, VectorHelper.createRotationalVector(15f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.1667f, VectorHelper.createRotationalVector(20f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.25f, VectorHelper.createRotationalVector(10f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.4167f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("leftArm",
				new Transformation(Transformation.Type.TRANSLATE,
					new Keyframe(0f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.1667f, VectorHelper.createTranslationalVector(0f, 2f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.4167f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("leftArm",
				new Transformation(Transformation.Type.ROTATE,
					new Keyframe(0f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.1667f, VectorHelper.createRotationalVector(-15f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.25f, VectorHelper.createRotationalVector(-25f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.3333f, VectorHelper.createRotationalVector(5f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.4167f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("rightArm",
				new Transformation(Transformation.Type.TRANSLATE,
					new Keyframe(0f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.1667f, VectorHelper.createTranslationalVector(0f, 2f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.4167f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("rightArm",
				new Transformation(Transformation.Type.ROTATE,
					new Keyframe(0f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.1667f, VectorHelper.createRotationalVector(15f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.25f, VectorHelper.createRotationalVector(25f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.3333f, VectorHelper.createRotationalVector(5f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.4167f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("leftLeg",
				new Transformation(Transformation.Type.TRANSLATE,
					new Keyframe(0f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.1667f, VectorHelper.createTranslationalVector(0f, 2f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.4167f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("leftLeg",
				new Transformation(Transformation.Type.ROTATE,
					new Keyframe(0f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.1667f, VectorHelper.createRotationalVector(15f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.25f, VectorHelper.createRotationalVector(20f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.3333f, VectorHelper.createRotationalVector(-5f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.4167f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("rightLeg",
				new Transformation(Transformation.Type.TRANSLATE,
					new Keyframe(0f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.1667f, VectorHelper.createTranslationalVector(0f, 2f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.4167f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("rightLeg",
				new Transformation(Transformation.Type.ROTATE,
					new Keyframe(0f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.1667f, VectorHelper.createRotationalVector(-15f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.25f, VectorHelper.createRotationalVector(-20f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.3333f, VectorHelper.createRotationalVector(5f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.4167f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("bag",
				new Transformation(Transformation.Type.TRANSLATE,
					new Keyframe(0f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.1667f, VectorHelper.createTranslationalVector(0f, 2f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.4167f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("bag",
				new Transformation(Transformation.Type.ROTATE,
					new Keyframe(0f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.1667f, VectorHelper.createRotationalVector(10f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.25f, VectorHelper.createRotationalVector(15f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.3333f, VectorHelper.createRotationalVector(-5f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.4167f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("body",
				new Transformation(Transformation.Type.TRANSLATE,
					new Keyframe(0f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.1667f, VectorHelper.createTranslationalVector(0f, 2f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.4167f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("body",
				new Transformation(Transformation.Type.ROTATE,
					new Keyframe(0f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.1667f, VectorHelper.createRotationalVector(-1f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.25f, VectorHelper.createRotationalVector(1f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.4167f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR))).build()
		);
		GIVE_REWARD = new KeyframeAnimation("giveReward", Animation.Builder.create(1.5416767f)
			.addBoneAnimation("head",
				new Transformation(Transformation.Type.ROTATE,
					new Keyframe(0f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.375f, VectorHelper.createRotationalVector(-7.5f, -50f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.4583f, VectorHelper.createRotationalVector(-7.5f, -40f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.6667f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.8333f, VectorHelper.createRotationalVector(15f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.9583f, VectorHelper.createRotationalVector(15f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.0833f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.25f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.5416767f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("rightArm",
				new Transformation(Transformation.Type.TRANSLATE,
					new Keyframe(0.625f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.75f, VectorHelper.createTranslationalVector(0f, -2f, -1f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.0833f, VectorHelper.createTranslationalVector(0f, -2f, -1f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.25f, VectorHelper.createTranslationalVector(0f, -2f, -1f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.5416767f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("rightArm",
				new Transformation(Transformation.Type.ROTATE,
					new Keyframe(0f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.125f, VectorHelper.createRotationalVector(-37.5f, 0f, -20f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.4583f, VectorHelper.createRotationalVector(-170f, 0f, -20f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.5417f, VectorHelper.createRotationalVector(-170f, 0f, -20f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.625f, VectorHelper.createRotationalVector(-60f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.75f, VectorHelper.createRotationalVector(-60f, 20f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.0833f, VectorHelper.createRotationalVector(-60f, 20f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.25f, VectorHelper.createRotationalVector(-60f, 20f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.5416767f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("bag",
				new Transformation(Transformation.Type.TRANSLATE,
					new Keyframe(0.4583f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.625f, VectorHelper.createTranslationalVector(7f, 0f, -6f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.75f, VectorHelper.createTranslationalVector(-3f, -7f, -12f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.0833f, VectorHelper.createTranslationalVector(-3f, -7f, -12f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.25f, VectorHelper.createTranslationalVector(-3f, -7f, -12f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.375f, VectorHelper.createTranslationalVector(7f, 0f, -6f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.5416767f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("bag",
				new Transformation(Transformation.Type.ROTATE,
					new Keyframe(0.4583f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.5417f, VectorHelper.createRotationalVector(5f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.625f, VectorHelper.createRotationalVector(0f, 90f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.75f, VectorHelper.createRotationalVector(-30f, 180f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.8333f, VectorHelper.createRotationalVector(-30f, 180f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.0833f, VectorHelper.createRotationalVector(-30f, 180f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.25f, VectorHelper.createRotationalVector(-30f, 180f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.375f, VectorHelper.createRotationalVector(0f, 90f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.4583433f, VectorHelper.createRotationalVector(5f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.5416767f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("leftArm",
				new Transformation(Transformation.Type.TRANSLATE,
					new Keyframe(0.4583f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.5833f, VectorHelper.createTranslationalVector(0f, -0.25f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.6667f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.75f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.8333f, VectorHelper.createTranslationalVector(0f, -2f, -1f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.25f, VectorHelper.createTranslationalVector(0f, -2f, -1f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.5416767f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("leftArm",
				new Transformation(Transformation.Type.ROTATE,
					new Keyframe(0.75f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.8333f, VectorHelper.createRotationalVector(-52.5f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.9167f, VectorHelper.createRotationalVector(-65f, -30f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.0833f, VectorHelper.createRotationalVector(-90f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.25f, VectorHelper.createRotationalVector(-90f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.5416767f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("body",
				new Transformation(Transformation.Type.TRANSLATE,
					new Keyframe(0.4583f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.5833f, VectorHelper.createTranslationalVector(0f, -0.25f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.6667f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.0833f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.5f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR))).build()
		);
		WALK = new KeyframeAnimation("walk", Animation.Builder.create(1.3433333f).looping()
			.addBoneAnimation("head",
				new Transformation(Transformation.Type.TRANSLATE,
					new Keyframe(0f, VectorHelper.createTranslationalVector(0f, 0f, -1f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.3433333f, VectorHelper.createTranslationalVector(0f, 0f, -1f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.6766666f, VectorHelper.createTranslationalVector(0f, 0f, -1f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1f, VectorHelper.createTranslationalVector(0f, 0f, -1f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.3433333f, VectorHelper.createTranslationalVector(0f, 0f, -1f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("head",
				new Transformation(Transformation.Type.ROTATE,
					new Keyframe(0f, VectorHelper.createRotationalVector(5f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.3433333f, VectorHelper.createRotationalVector(5f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.6766666f, VectorHelper.createRotationalVector(5f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1f, VectorHelper.createRotationalVector(5f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.3433333f, VectorHelper.createRotationalVector(5f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("leftArm",
				new Transformation(Transformation.Type.TRANSLATE,
					new Keyframe(0f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.3433333f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.6766666f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.3433333f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("leftArm",
				new Transformation(Transformation.Type.ROTATE,
					new Keyframe(0f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.3433333f, VectorHelper.createRotationalVector(35f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.6766666f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1f, VectorHelper.createRotationalVector(-35f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.3433333f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("rightArm",
				new Transformation(Transformation.Type.TRANSLATE,
					new Keyframe(0f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.3433333f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.6766666f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.3433333f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("rightArm",
				new Transformation(Transformation.Type.ROTATE,
					new Keyframe(0f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.3433333f, VectorHelper.createRotationalVector(-35f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.6766666f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1f, VectorHelper.createRotationalVector(35f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.3433333f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("leftLeg",
				new Transformation(Transformation.Type.TRANSLATE,
					new Keyframe(0f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.3433333f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.6766666f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.3433333f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("leftLeg",
				new Transformation(Transformation.Type.ROTATE,
					new Keyframe(0f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.3433333f, VectorHelper.createRotationalVector(25f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.6766666f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1f, VectorHelper.createRotationalVector(-25f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.3433333f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("rightLeg",
				new Transformation(Transformation.Type.TRANSLATE,
					new Keyframe(0f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.3433333f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.6766666f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.3433333f, VectorHelper.createTranslationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("rightLeg",
				new Transformation(Transformation.Type.ROTATE,
					new Keyframe(0f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.3433333f, VectorHelper.createRotationalVector(-25f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.6766666f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1f, VectorHelper.createRotationalVector(25f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.3433333f, VectorHelper.createRotationalVector(0f, 0f, 0f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("body",
				new Transformation(Transformation.Type.TRANSLATE,
					new Keyframe(0f, VectorHelper.createTranslationalVector(0f, 0f, -1f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.3433333f, VectorHelper.createTranslationalVector(0f, 0f, -1f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.6766666f, VectorHelper.createTranslationalVector(0f, 0f, -1f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1f, VectorHelper.createTranslationalVector(0f, 0f, -1f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.3433333f, VectorHelper.createTranslationalVector(0f, 0f, -1f),
						Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("body",
				new Transformation(Transformation.Type.ROTATE,
					new Keyframe(0f, VectorHelper.createRotationalVector(5f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.3433333f, VectorHelper.createRotationalVector(5f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(0.6766666f, VectorHelper.createRotationalVector(5f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1f, VectorHelper.createRotationalVector(5f, 0f, 0f),
						Transformation.Interpolations.LINEAR),
					new Keyframe(1.3433333f, VectorHelper.createRotationalVector(5f, 0f, 0f),
						Transformation.Interpolations.LINEAR))).build()
		);
		ANIMATIONS = new ArrayList<>()
		{{
			add(IDLE);
			add(NOD);
			add(GIVE_REWARD);
			add(WALK);
		}};
	}
}