name: 'Crash Report'
description: 'Use this template if your game is crashing or failing to start correctly'
labels: [ "crash" ]
assignees:
    - Faboslav
body:
    -   type: markdown
        attributes:
            value: |
                Thanks for taking the time to fill out this crash report! Anyhow before you take your time answering all of the question please make sure of the following:
                  - Are you sure that there is not already reported same or similar crash? You can try to use the [search](https://github.com/Faboslav/friends-and-foes/issues).
                  - Are you using the latest version of the mod? You can find the latest version [here](https://github.com/Faboslav/friends-and-foes/releases).
    -   type: input
        id: minecraft-version
        attributes:
            label: 'Minecraft version information'
            description: 'Please provide the exact minecraft version that you are using.'
            placeholder: 'Example: 1.19.2'
        validations:
            required: true
    -   type: dropdown
        id: mod-loader
        attributes:
            label: 'Mod loader information'
            description: 'Please choose the mod loader that you are using.'
            options:
                - Fabric
                - Quilt
                - Forge
                - NeoForge
        validations:
            required: true
    -   type: input
        id: mod-loader-version
        attributes:
            label: 'Mod loader version information'
            description: 'Please provide the exact mod loader version that you are using.'
            placeholder: 'Example: 0.13.3 (Fabric) or 40.0.32 (Forge)'
        validations:
            required: true
    -   type: input
        id: mod-version
        attributes:
            label: 'Mod version information'
            description: 'Please provide the exact mod version that you are using.'
            placeholder: 'Example: 1.0.0'
        validations:
            required: true
    -   type: textarea
        id: reproduction-steps
        attributes:
            label: 'Reproduction Steps'
            description: 'Provide information on how to reproduce this bug. Make sure your instructions are minimal and clear.'
            placeholder: |
                Example:
                1. Spawn mob using spawn egg
                2. Wait for some action
                3. Nothing happens
        validations:
            required: true
    -   type: textarea
        id: report
        attributes:
            label: 'Crash Report and latest.log'
            description: 'Latest crash report generated by your minecraft client. Crash report file should be located in `crash-report` directory and latest.log file should be located in `logs` directory. Uploading both of these files is critical in resolving your issue!'
            placeholder: 'You can attach your crash report and latest.log by dragging & dropping them to this textbox.'
        validations:
            required: true
    -   type: textarea
        id: screenshots-and-files
        attributes:
            label: 'Additional information'
            description: 'List of other mods that you are using. If appropriate, add screenshots or other files to help explain your problem.'
            placeholder: 'You can attach your files by dragging & dropping them to this textbox.'
        validations:
            required: false