modLoader = "javafml"
loaderVersion = "*"
license = "${modLicense}"
issueTrackerURL = "${modGitHub}/issues"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
authors = "${modAuthor}"
description = "${modDescription}"
logoFile = "icon.png"
logoBlur = false
displayURL = "${modGitHub}"

[[mixins]]
config = "friendsandfoes-neoforge.mixins.json"

[[mixins]]
config = "friendsandfoes-common.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.${ modId }]]
modId = "neoforge"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ modId }]]
modId = "minecraft"
type = "required"
versionRange = "[${minMinecraftVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ modId }]]
modId = "yet_another_config_lib_v3"
type = "required"
versionRange = "[${yaclVersion},)"
ordering = "NONE"
side = "BOTH"
[dependencies.${ modId }.mc-publish]
ignore = false
modrinth = "yacl"
curseforge = "yacl"

[[dependencies.${ modId }]]
modId = "resourcefullib"
type = "required"
versionRange = "[${resourcefulLibLibVersion},)"
ordering = "NONE"
side = "BOTH"
[dependencies.${ modId }.mc-publish]
ignore = false
modrinth = "resourceful-lib"
curseforge = "resourceful-lib"

[modproperties.${ modId }]
catalogueImageIcon = "catalogue_icon.png"
catalogueBackground = "catalogue_background.png"
configuredBackground = "catalogue_background.png"