# Stonecutter
stonecutter_enabled_platforms=fabric, neoforge

# Java
java.version=25

# Minecraft
minecraft_version=26.3
min_minecraft_version=26.3

# Mappings
deps.parchment=

# Fabric
deps.fabric_loader=0.19.5
deps.fabric_api=0.161.0
deps.fabric_gametest_api=4.0.22+4a7fa0819e

# NeoForge
deps.neoforge=26.3.0.7-beta

# Dependencies
deps.resourceful_lib.mc=26.3
deps.resourceful_lib.lib=6.0.0
deps.yacl=3.9.7+26.3
deps.mod_menu=21.0.0-beta.1
deps.trinkets=
deps.curios=
