name: "Publish legacy"

on:
    workflow_dispatch:
        inputs:
            mod_loaders:
                description: 'List of mod loaders to be published'
                required: true
                default: "['fabric', 'forge', 'neoforge']"
                type: string
            branches:
                description: 'List of branches to be published'
                required: true
                default: "['1.19.2', '1.19.3', '1.19.4', '1.20.1', '1.20.2', '1.20.4', '1.20.6']"
                type: string

jobs:
    publish:
        name: "Publish"
        strategy:
            fail-fast: false
            matrix:
                branch: ${{ fromJson(inputs.branches) }}
        uses: ./.github/workflows/publish-branch-legacy.yml
        with:
            branch: ${{ matrix.branch }}
            mod_loaders: ${{ inputs.mod_loaders }}
        secrets: inherit